### ISSUE TITLE
Attempting to update a non-existant record results in a 500 response

### ISSUE THREAD

**Issue by marrold** [frillip/noip-rfc2136#6]
I wasn't going to raise this one but as there's a bit of activity it's reminded me - if you try to update a DNS record that doesn't exist the logs show an exception and the server replies with a 500 error.

This raised a few questions:

1) Should noip-rfc2136 be able to _create_ new records? Maybe there should be a config option so the user can decide?
2) Should noip-rfc2136 catch the exception and send a more meaningful reply?

Having checked the code this is because `resolver.query(fqdn, 'A')` fails. There's an attempt to catch the exception but it's attempting to print `current_ip` to the log which hasn't been assigned, so it causes the below exception:

    Error handling request
    Traceback (most recent call last):
      File "/opt/venv/noip-rfc2136.py", line 73, in GetCurrentIP
        answer = resolver.query(fqdn, 'A')
      File "/opt/venv/lib/python3.8/site-packages/dns/resolver.py", line 1002, in query
        raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
    dns.resolver.NXDOMAIN: The DNS query name does not exist: pi-11.wd18.marrold.co.uk.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
        resp = await request_handler(request)
      File "/opt/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
        resp = await handler(request)
      File "/opt/venv/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 117, in impl
        return await handler(request)
      File "/opt/venv/lib/python3.8/site-packages/aiohttp_basicauth_middleware/__init__.py", line 79, in middleware
        return await handler(request)
      File "/opt/venv/noip-rfc2136.py", line 156, in UpdateReq
        current_ip = GetCurrentIP(fqdn)
      File "/opt/venv/noip-rfc2136.py", line 80, in GetCurrentIP
        logger.debug('No IP in DNS for ' + str(current_ip))
    UnboundLocalError: local variable 'current_ip' referenced before assignment

**Comment by frillip** [comment]
So the fix for this is to edit line 80 to be:
```
logger.debug('No IP in DNS for ' + str(fqdn))
```

However, you're correct in that it will then add a new record if it does not exist. Useful if the record is deleted for some reason, eg host is offline, but potentially unwanted behaviour otherwise. The [dnspython documentation](https://dnspython.readthedocs.io/en/latest/message-update.html) is somewhat ambiguous on what happens when you try to update a record that does not exist, but in my case, BIND9 treats this no different to an add record operation. I'll update it to deny an update if the host does not exist. Checking the [No-IP API responses](https://www.noip.com/integrate/response), it seems like `nohost` would be the most appropriate resonse.

It might be worth adding a configuration option to the DNS section such as `create_enabled` that would allow record creation if desired.

**Comment by marrold** [comment]
Ah I think we both looked at the same time. Adding a `create_enabled` option sounds sensible, would you to implement it or should I?

**Comment by frillip** [comment]
I'll implement it along with the YAML config file.

I also found a separate bug that I need to fix where it'll try and update records ending with the dns zone, eg `thisdoesntexistwd18.marrold.co.uk`

**Comment by marrold** [comment]
Cheers Phil, looks good!
